import { StyleSheet, Dimensions } from "react-native";

const colors = {
  background: "#f5f5f0",
  primary: "#3e2723",
  accent: "#5d4037",
  buttonBase: "#ffffff",
  buttonAccent: "#8d6e63",
  textPrimary: "#3e2723",
  textLight: "#f1f5f9",
  highlight: "#8d6e63",
  disabled: "#d7ccc8",
  teamButton: "#5d4037",
  materialsButton: "#6d4c41",
  buttonText: "#ffffff",
  border: "#a1887f",
  cardBackground: "#efebe9"
};

export const createAdaptiveStyles = (isLandscape: boolean, screenWidth: number, screenHeight: number) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      overflow: "hidden",
      width: "100%",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: colors.primary,
      paddingVertical: isLandscape ? 10 : 18,
      paddingHorizontal: 20,
      width: "100%",
      height: isLandscape ? 50 : 70,
      borderBottomWidth: 1,
      borderBottomColor: colors.accent,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    headerRight: {
      flexDirection: "row",
      alignItems: "center",
    },
    iconButton: {
      padding: isLandscape ? 8 : 10,
      borderRadius: 24,
      backgroundColor: colors.accent,
      marginLeft: isLandscape ? 6 : 8,
    },
    title: {
      fontSize: isLandscape ? 18 : 20,
      fontWeight: "600",
      color: colors.textLight,
      marginLeft: 16,
      letterSpacing: 0.5,
    },
    content: {
      flex: 1,
      position: "relative",
      overflow: "hidden",
      width: "100%",
    },
    modeContainer: {
      position: "absolute",
      width: screenWidth,
      height: "100%",
      left: 0,
    },
    mapContainer: {
      padding: isLandscape ? 12 : 20,
      flex: 1,
      width: screenWidth,
      backgroundColor: colors.background,
    },
    timerContainer: {
      alignItems: "center",
      marginVertical: isLandscape ? 12 : 20,
      width: "100%",
    },
    controlButtonContainer: {
      alignItems: "center",
      marginTop: isLandscape ? 12 : 20,
      width: "100%",
    },
    manualContainer: {
      position: "absolute",
      width: screenWidth,
      height: "100%",
      left: 0,
      backgroundColor: colors.background,
      paddingTop: isLandscape ? 12 : 20,
    },
    modeToggleContainer: {
      position: "absolute",
      bottom: isLandscape ? 16 : 24,
      right: isLandscape ? 16 : 24,
      zIndex: 10,
      backgroundColor: colors.accent,
      borderRadius: 24,
      padding: 8,
      elevation: 2,
    },
    teamButton: {
      position: 'absolute',
      backgroundColor: colors.teamButton,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isLandscape ? 10 : 12,
      paddingHorizontal: isLandscape ? 16 : 20,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      zIndex: 20,
    },
    teamButtonText: {
      color: colors.buttonText,
      fontSize: isLandscape ? 14 : 16,
      fontWeight: '500',
      marginLeft: 8,
      letterSpacing: 0.3,
    },
    materialsButton: {
      position: 'absolute',
      backgroundColor: colors.materialsButton,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isLandscape ? 10 : 12,
      paddingHorizontal: isLandscape ? 16 : 20,
      borderRadius: 30,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 4,
      zIndex: 20,
    },
    materialsButtonText: {
      color: colors.buttonText,
      fontSize: isLandscape ? 14 : 16,
      fontWeight: '500',
      marginLeft: 8,
      letterSpacing: 0.3,
    },
  });
};

const DeviceControlStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    overflow: "hidden",
    width: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 20,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconButton: {
    padding: 10,
    borderRadius: 24,
    backgroundColor: colors.accent,
    marginLeft: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: "600",
    color: colors.textLight,
    marginLeft: 16,
    letterSpacing: 0.5,
  },
  content: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    width: "100%",
  },
  modeContainer: {
    position: "absolute",
    width: Dimensions.get("window").width,
    height: "100%",
    left: 0,
  },
  mapContainer: {
    padding: 20,
    flex: 1,
    width: Dimensions.get("window").width,
    backgroundColor: colors.background,
  },
  timerContainer: {
    alignItems: "center",
    marginVertical: 20,
    width: "100%",
  },
  controlButtonContainer: {
    alignItems: "center",
    marginTop: 20,
    width: "100%",
  },
  manualContainer: {
    position: "absolute",
    width: Dimensions.get("window").width,
    height: "100%",
    left: 0,
    backgroundColor: colors.background,
    paddingTop: 20,
  },
  modeToggleContainer: {
    position: "absolute",
    bottom: 24,
    right: 24,
    zIndex: 10,
    backgroundColor: colors.accent,
    borderRadius: 24,
    padding: 8,
    elevation: 2,
  },
  teamButton: {
    position: 'absolute',
    backgroundColor: colors.teamButton,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 20,
    bottom: 24,
    right: 24,
  },
  teamButtonText: {
    color: colors.buttonText,
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
    letterSpacing: 0.3,
  },
  materialsButton: {
    position: 'absolute',
    backgroundColor: colors.materialsButton,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 20,
    bottom: 24,
    left: 24,
  },
  materialsButtonText: {
    color: colors.buttonText,
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
    letterSpacing: 0.3,
  },
});

export default DeviceControlStyles;